from django.test import TestCase
from django.urls import reverse
from django.utils import translation

from .models import Service


class ServiceTests(TestCase):
    def setUp(self):
        # Force the test to run in English so assertions are deterministic.
        translation.activate("en")
        self.service = Service.objects.create(
            name="Website Development",
            name_fa="طراحی وب‌سایت",
            short_description="Test",
            active=True,
        )

    def test_slug_autogenerated(self):
        self.assertTrue(self.service.slug)

    def test_list_view(self):
        url = reverse("services:list")
        r = self.client.get(url)
        self.assertEqual(r.status_code, 200)
        # The template uses name_fa when present, so check for the Persian name too.
        # A simple robust check is that the service's detail URL is present.
        self.assertContains(r, self.service.get_absolute_url())

    def test_detail_view(self):
        url = self.service.get_absolute_url()
        r = self.client.get(url)
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, self.service.name_fa)