# Generated by Django 6.1.1 on 2026-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Default / English name', max_length=120)),
                ('name_fa', models.CharField(blank=True, max_length=120)),
                ('name_ps', models.CharField(blank=True, max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('short_description_fa', models.CharField(blank=True, max_length=255)),
                ('short_description_ps', models.CharField(blank=True, max_length=255)),
                ('short_description_en', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('description_ps', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='e.g. bi-globe', max_length=60)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
    ]
