# Generated by Django 6.1.1 on 2026-09-12 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('language', models.CharField(choices=[('fa', 'Dari/Persian'), ('ps', 'Pashto'), ('en', 'English')], default='fa', max_length=2)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_fa', models.CharField(max_length=60)),
                ('label_ps', models.CharField(blank=True, max_length=60)),
                ('label_en', models.CharField(blank=True, max_length=60)),
                ('url_name', models.CharField(help_text='Django URL name e.g. pages:home', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Binyad', max_length=120)),
                ('name_fa', models.CharField(default='بنیاد', max_length=120)),
                ('name_ps', models.CharField(default='بنیاد', max_length=120)),
                ('name_en', models.CharField(default='Binyad', max_length=120)),
                ('tagline_fa', models.CharField(default='راه\u200cحل\u200cهای مدیریت، اداری و تکنالوژی', max_length=255)),
                ('tagline_ps', models.CharField(blank=True, max_length=255)),
                ('tagline_en', models.CharField(default='Business, Management & IT Solutions', max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='brand/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp'])])),
                ('favicon', models.ImageField(blank=True, upload_to='brand/')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, help_text='International format without +, e.g. 93700000000', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_fa', models.CharField(blank=True, max_length=255)),
                ('address_ps', models.CharField(blank=True, max_length=255)),
                ('address_en', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('opening_hours_fa', models.CharField(blank=True, max_length=255)),
                ('opening_hours_ps', models.CharField(blank=True, max_length=255)),
                ('opening_hours_en', models.CharField(blank=True, max_length=255)),
                ('google_maps_url', models.URLField(blank=True)),
                ('footer_text_fa', models.TextField(blank=True)),
                ('footer_text_ps', models.TextField(blank=True)),
                ('footer_text_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('position_fa', models.CharField(blank=True, max_length=120)),
                ('position_ps', models.CharField(blank=True, max_length=120)),
                ('position_en', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
