# Generated by Django 6.1.1 on 2026-09-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('title_fa', models.CharField(blank=True, max_length=160)),
                ('title_ps', models.CharField(blank=True, max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('description_ps', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False, help_text='Marks this entry as a demo/sample, not real client work')),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.portfolioproject')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
